import style from './editCustomerForm.module.scss';

export const editCustomerFormField = [
  {
    tagType: 'enabled',
    label: "Enabled",
    labelClass: style.form__label,
    inputClass: style.form__input,
    errorClass: style.form__error,
    id: "enabled",
    name: "enabled",
    type: "select",
    options: ["true", "false"],
  },
  {
    tagType: 'regular',
    label: "CustomerNo",
    labelClass: style.form__label,
    inputClass: style.form__input,
    errorClass: style.form__error,
    id: "customerNo",
    name: "customerNo",
    type: "number",
    placeholder: "Enter customerNo",
  },
  {
    tagType: 'regular',
    label: "First Name",
    labelClass: style.form__label,
    inputClass: style.form__input,
    errorClass: style.form__error,
    id: "firstName",
    name: "firstName",
    type: "text",
    placeholder: "Enter First Name",
  },
  {
    tagType: 'regular',
    label: "Last Name",
    labelClass: style.form__label,
    inputClass: style.form__input,
    errorClass: style.form__error,
    id: "lastName",
    name: "lastName",
    type: "text",
    placeholder: "Enter Last Name",
  },
  {
    tagType: 'regular',
    label: "Email",
    labelClass: style.form__label,
    inputClass: style.form__input,
    errorClass: style.form__error,
    id: "email",
    name: "email",
    type: "text",
    placeholder: "Enter Email",
  },
  {
    tagType: 'regular',
    label: "VAT Nr",
    labelClass: style.form__label,
    inputClass: style.form__input,
    errorClass: style.form__error,
    id: "vatNr",
    name: "vatNr",
    type: "number",
    placeholder: "Enter VAT Nr",
  },
];